In [52]:
# import basic packages and load the data

import numpy as np
import pandas as pd

tour_comp = pd.read_csv("data/TourneyCompactResults.csv")
seeds = pd.read_csv("data/TourneySeeds.csv")
slots = pd.read_csv("data/TourneySlots.csv")

In [54]:
tour_comp.tail()

Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
2045    2016     146   1314      88   1323      74    N      0
2046    2016     146   1393      68   1438      62    N      0
2047    2016     152   1314      83   1393      66    N      0
2048    2016     152   1437      95   1328      51    N      0
2049    2016     154   1437      77   1314      74    N      0

In [55]:
seeds.tail()

Season Seed  Team
2145    2017  Z12  1292
2146    2017  Z13  1457
2147    2017  Z14  1245
2148    2017  Z15  1297
2149    2017  Z16  1411

In [56]:
# we can see that we have the seeds information for 2017 season, but no tour results
# since we are going to use seeds difference here as a feature, we need only the numbers
seeds.shape

(2150, 3)

In [57]:
# reset the seeds information with only numbers
for i in range(2150):
    seeds.Seed[i] = int(seeds.Seed[i][1:3])

/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()


In [62]:
# merge the two tables to get the seeds information of both Wteam and Lteam
data = pd.merge(tour_comp, seeds, how='left', left_on=["Season","Wteam"], right_on=["Season","Team"])
data = pd.merge(data, seeds, how='left', left_on=["Season","Lteam"], right_on=["Season","Team"])
data.tail()

Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot Seed_x  Team_x  \
2045    2016     146   1314      88   1323      74    N      0      1    1314   
2046    2016     146   1393      68   1438      62    N      0     10    1393   
2047    2016     152   1314      83   1393      66    N      0      1    1314   
2048    2016     152   1437      95   1328      51    N      0      2    1437   
2049    2016     154   1437      77   1314      74    N      0      2    1437   

     Seed_y  Team_y  
2045      6    1323  
2046      1    1438  
2047     10    1393  
2048      2    1328  
2049      1    1314

In [63]:
# check the data shape to make sure we merge it right
print(tour_comp.shape);
print(data.shape)

(2050, 8)
(2050, 12)


In [64]:
# drop the columns we do not need
data0 = data[[0,1,2,8,4,10,6,7]]
data = data[[0,2,8,4,10]]
data.tail()

Season  Wteam Seed_x  Lteam Seed_y
2045    2016   1314      1   1323      6
2046    2016   1393     10   1438      1
2047    2016   1314      1   1393     10
2048    2016   1437      2   1328      2
2049    2016   1437      2   1314      1

In [5]:
# now we need to add seed difference and the game result represented by 1 or 0
# since in this table the Wteam is al

In [15]:
b.head()

Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot Seed_x  Team_x  \
0    1985     136   1116      63   1234      54    N      0      9    1116   
1    1985     136   1120      59   1345      58    N      0     11    1120   
2    1985     136   1207      68   1250      43    N      0      1    1207   
3    1985     136   1229      58   1425      55    N      0      9    1229   
4    1985     136   1242      49   1325      38    N      0      3    1242   

  Seed_y  Team_y  
0      8    1234  
1      6    1345  
2     16    1250  
3      8    1425  
4     14    1325

In [6]:
c = b[[0,1,2,8,4,10,6,7]]

In [11]:
c.shape

(2050, 8)

In [16]:
c.head()

Season  Daynum  Wteam Seed_x  Lteam Seed_y Wloc  Numot  Seed_diff  win
0    1985     136   1116      9   1234      8    N      0         -1    1
1    1985     136   1120     11   1345      6    N      0         -5    1
2    1985     136   1207      1   1250     16    N      0         15    1
3    1985     136   1229      9   1425      8    N      0         -1    1
4    1985     136   1242      3   1325     14    N      0         11    1

In [17]:
Seed_diff = np.arange(2050)
c["Seed_diff"] = Seed_diff

/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app


In [18]:
c.head()

Season  Daynum  Wteam Seed_x  Lteam Seed_y Wloc  Numot  Seed_diff  win
0    1985     136   1116      9   1234      8    N      0          0    1
1    1985     136   1120     11   1345      6    N      0          1    1
2    1985     136   1207      1   1250     16    N      0          2    1
3    1985     136   1229      9   1425      8    N      0          3    1
4    1985     136   1242      3   1325     14    N      0          4    1

In [19]:
for i in range(2050):
    c.set_value(i,"Seed_diff",c.Seed_y[i] - c.Seed_x[i]) 
    #print(c.Seed_diff[i],c.Seed_x[i],c.Seed_y[i])

In [20]:
c.head()

Season  Daynum  Wteam Seed_x  Lteam Seed_y Wloc  Numot  Seed_diff  win
0    1985     136   1116      9   1234      8    N      0         -1    1
1    1985     136   1120     11   1345      6    N      0         -5    1
2    1985     136   1207      1   1250     16    N      0         15    1
3    1985     136   1229      9   1425      8    N      0         -1    1
4    1985     136   1242      3   1325     14    N      0         11    1

In [21]:
win = np.repeat(1,2050)
win

array([1, 1, 1, ..., 1, 1, 1])

In [22]:
c["win"] = win

/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':


In [23]:
c.head()

Season  Daynum  Wteam Seed_x  Lteam Seed_y Wloc  Numot  Seed_diff  win
0    1985     136   1116      9   1234      8    N      0         -1    1
1    1985     136   1120     11   1345      6    N      0         -5    1
2    1985     136   1207      1   1250     16    N      0         15    1
3    1985     136   1229      9   1425      8    N      0         -1    1
4    1985     136   1242      3   1325     14    N      0         11    1

In [24]:
d = c[[9,8]]

In [25]:
d.head()

win  Seed_diff
0    1         -1
1    1         -5
2    1         15
3    1         -1
4    1         11

In [26]:
for i in range(1000):
    d.set_value(i,"win",0)
    d.set_value(i,"Seed_diff",0-d.Seed_diff[i])

In [27]:
d.head()

win  Seed_diff
0    0          1
1    0          5
2    0        -15
3    0          1
4    0        -11

In [28]:
win = np.array(d.win)
seed_diff = np.array(d.Seed_diff)

In [33]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.metrics import confusion_matrix, precision_score, recall_score
from sklearn.model_selection import cross_val_score

In [35]:
x_train, x_test, y_train, y_test = train_test_split(seed_diff, win, random_state=0)

In [41]:
log = LogisticRegression().fit(x_train, y_train)


/anaconda/lib/python3.6/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


ValueError: Found input variables with inconsistent numbers of samples: [1, 1537]

In [42]:
x_train = x_train.reshape(-1,1)
x_test = x_test.reshape(-1,1)

In [49]:
log = LogisticRegression().fit(x_train, y_train)

In [44]:
print(log.score(x_test,y_test))

0.729044834308


In [45]:
log = LogisticRegression()
scores = cross_val_score(log, x_train, y_train, cv=5)

In [47]:
print(scores)

[ 0.73139159  0.70032573  0.69381107  0.72964169  0.72638436]


In [51]:
pred = log.predict(x_test)
confusion = confusion_matrix(y_test,pred)
print(confusion);
print(precision_score(y_test,pred));
print(recall_score(y_test,pred))

[[185  74]
 [ 65 189]]
0.718631178707
0.744094488189
