In [50]:
import numpy as np
import pandas as pd

data = pd.read_csv("all_data.csv")
data.head()

Unnamed: 0  team2  Season       fgm1       fga1     fgm31      fga31  \
0           0   1125    2013  27.633333  55.966667  8.300000  22.100000   
1           1   1137    2006  23.000000  48.827586  6.034483  15.586207   
2           2   1139    2013  23.939394  53.363636  6.545455  19.060606   
3           3   1156    2009  23.031250  54.156250  4.750000  15.343750   
4           4   1160    2012  22.718750  51.687500  5.562500  16.312500   

        ftm1       fta1        or1    ...     diff_fga3  diff_ftm  diff_fta  \
0  13.333333  18.133333   9.366667    ...      1.006250 -2.229167 -2.679167   
1  14.275862  20.655172   9.310345    ...     -1.220245 -1.304783 -1.796440   
2  14.000000  20.333333  11.606061    ...      6.216856 -0.437500  0.989583   
3  14.156250  20.093750  11.562500    ...     -0.312500 -0.531250  0.093750   
4  15.281250  22.250000   9.562500    ...     -1.535985 -0.082386  1.825758   

    diff_or   diff_dr  diff_ast   diff_to  diff_stl  diff_blk   diff_pf  
0 -2.164583 -1.885417  1.956250  0.472917  2.595833 -1.172917  1.856250  
1 -2.883204 -0.459399 -0.962180  1.095662  0.272525 -4.439377  0.616240  
2  2.574811 -2.246212 -0.558712  3.835227  2.166667 -1.759470  3.404356  
3  0.468750 -0.656250 -1.000000 -0.125000  2.625000  0.218750  2.750000  
4 -2.558712  1.340909 -3.352273 -1.285985 -1.761364 -1.386364 -0.542614  

[5 rows x 65 columns]

In [51]:
data0 = data.iloc[:,50:65]
data1 = data.iloc[:,1:3]

In [52]:
data0 = pd.concat([data1,data0], axis=1)
data0.tail()

team2  Season  different_seed  diff_score  diff_fgm  diff_fga  diff_fgm3  \
909   1462    2015               5    0.933824  1.404412 -2.812500  -0.174632   
910   1462    2016              13    6.827621  2.439516  7.852823  -0.406250   
911   1462    2016               5   12.468750  3.906250  5.937500   1.000000   
912   1463    2016              -7   -1.831019 -0.627315 -1.837963   0.219907   
913   1463    2016              -8   -6.973064 -1.239057 -3.720539  -2.865320   

     diff_fga3  diff_ftm  diff_fta   diff_or   diff_dr  diff_ast   diff_to  \
909  -1.095588 -1.700368 -0.748162 -2.406250 -0.332721  3.569853  0.744485   
910  -1.193548  2.354839  1.419355  4.675403 -0.514113  3.375000 -0.991935   
911   2.562500  3.656250  4.312500  1.625000  4.468750  4.781250  1.781250   
912   0.696759 -0.796296  0.868056 -0.081019  3.596065 -2.019676  0.668981   
913  -6.710438 -1.629630 -0.444444  1.239057  2.723906  1.589226  3.602694   

     diff_stl  diff_blk   diff_pf  
909 -0.505515 -0.834559 -1.503676  
910  2.635081 -0.260081  2.090726  
911  1.437500 -0.125000  3.250000  
912 -2.126157  0.549769 -1.443287  
913 -0.801347  0.336700  1.326599

In [53]:
data0 = pd.concat([data['team1'],data0], axis=1)
data0.head()

team1  team2  Season  different_seed  diff_score  diff_fgm  diff_fga  \
0   1112   1125    2013              -5    3.618750  2.602083  0.310417   
1   1116   1137    2006              -1   -8.012236 -3.516129 -8.914349   
2   1137   1139    2013               5    1.174242 -0.154356  0.457386   
3   1112   1156    2009              -1   -7.218750 -2.625000  0.093750   
4   1124   1160    2012              -8   -7.991477 -3.372159 -4.312500   

   diff_fgm3  diff_fga3  diff_ftm  diff_fta   diff_or   diff_dr  diff_ast  \
0   0.643750   1.006250 -2.229167 -2.679167 -2.164583 -1.885417  1.956250   
1   0.324805  -1.220245 -1.304783 -1.796440 -2.883204 -0.459399 -0.962180   
2   1.920455   6.216856 -0.437500  0.989583  2.574811 -2.246212 -0.558712   
3  -1.437500  -0.312500 -0.531250  0.093750  0.468750 -0.656250 -1.000000   
4  -1.164773  -1.535985 -0.082386  1.825758 -2.558712  1.340909 -3.352273   

    diff_to  diff_stl  diff_blk   diff_pf  
0  0.472917  2.595833 -1.172917  1.856250  
1  1.095662  0.272525 -4.439377  0.616240  
2  3.835227  2.166667 -1.759470  3.404356  
3 -0.125000  2.625000  0.218750  2.750000  
4 -1.285985 -1.761364 -1.386364 -0.542614

In [54]:
data0 = pd.concat([data['result'],data0], axis=1)
data0 = data0.dropna()
data0.head()

result  team1  team2  Season  different_seed  diff_score  diff_fgm  \
0       1   1112   1125    2013              -5    3.618750  2.602083   
1       0   1116   1137    2006              -1   -8.012236 -3.516129   
2       0   1137   1139    2013               5    1.174242 -0.154356   
3       1   1112   1156    2009              -1   -7.218750 -2.625000   
4       1   1124   1160    2012              -8   -7.991477 -3.372159   

   diff_fga  diff_fgm3  diff_fga3  diff_ftm  diff_fta   diff_or   diff_dr  \
0  0.310417   0.643750   1.006250 -2.229167 -2.679167 -2.164583 -1.885417   
1 -8.914349   0.324805  -1.220245 -1.304783 -1.796440 -2.883204 -0.459399   
2  0.457386   1.920455   6.216856 -0.437500  0.989583  2.574811 -2.246212   
3  0.093750  -1.437500  -0.312500 -0.531250  0.093750  0.468750 -0.656250   
4 -4.312500  -1.164773  -1.535985 -0.082386  1.825758 -2.558712  1.340909   

   diff_ast   diff_to  diff_stl  diff_blk   diff_pf  
0  1.956250  0.472917  2.595833 -1.172917  1.856250  
1 -0.962180  1.095662  0.272525 -4.439377  0.616240  
2 -0.558712  3.835227  2.166667 -1.759470  3.404356  
3 -1.000000 -0.125000  2.625000  0.218750  2.750000  
4 -3.352273 -1.285985 -1.761364 -1.386364 -0.542614

In [55]:
df = data0.iloc[:,4:19]
df.head()

different_seed  diff_score  diff_fgm  diff_fga  diff_fgm3  diff_fga3  \
0              -5    3.618750  2.602083  0.310417   0.643750   1.006250   
1              -1   -8.012236 -3.516129 -8.914349   0.324805  -1.220245   
2               5    1.174242 -0.154356  0.457386   1.920455   6.216856   
3              -1   -7.218750 -2.625000  0.093750  -1.437500  -0.312500   
4              -8   -7.991477 -3.372159 -4.312500  -1.164773  -1.535985   

   diff_ftm  diff_fta   diff_or   diff_dr  diff_ast   diff_to  diff_stl  \
0 -2.229167 -2.679167 -2.164583 -1.885417  1.956250  0.472917  2.595833   
1 -1.304783 -1.796440 -2.883204 -0.459399 -0.962180  1.095662  0.272525   
2 -0.437500  0.989583  2.574811 -2.246212 -0.558712  3.835227  2.166667   
3 -0.531250  0.093750  0.468750 -0.656250 -1.000000 -0.125000  2.625000   
4 -0.082386  1.825758 -2.558712  1.340909 -3.352273 -1.285985 -1.761364   

   diff_blk   diff_pf  
0 -1.172917  1.856250  
1 -4.439377  0.616240  
2 -1.759470  3.404356  
3  0.218750  2.750000  
4 -1.386364 -0.542614

In [56]:
target = data0['result']
target.head()

0    1
1    0
2    0
3    1
4    1
Name: result, dtype: int64

In [86]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.metrics import confusion_matrix, precision_score, recall_score
from sklearn.model_selection import cross_val_score
from sklearn import preprocessing

x_train, x_test, y_train, y_test = train_test_split(df, target, random_state=0)

x_train_scaled = preprocessing.MinMaxScaler().fit(x_train).transform(x_train)
x_test_scaled = preprocessing.MinMaxScaler().fit(x_train).transform(x_test)
df_scaled = preprocessing.MinMaxScaler().fit_transform(df)

In [71]:
# logistic regression
log = LogisticRegression().fit(x_train_scaled, y_train)
print(log.score(x_test_scaled,y_test));

pred = log.predict(x_test_scaled)
confusion = confusion_matrix(y_test,pred)
print(confusion);
print(precision_score(y_test,pred));
print(recall_score(y_test,pred));

logreg = LogisticRegression()
scores = cross_val_score(logreg, df_scaled, target, cv=5)
print(scores)

0.713656387665
[[85 27]
 [38 77]]
0.740384615385
0.669565217391
[ 0.75824176  0.68131868  0.74175824  0.71270718  0.69444444]


In [87]:
# svm
from sklearn import svm
clf = svm.SVC()

print(clf.fit(x_train_scaled, y_train).score(x_test_scaled,y_test));

pred = clf.fit(x_train_scaled, y_train).predict(x_test_scaled)
confusion = confusion_matrix(y_test,pred)
print(confusion);
print(precision_score(y_test,pred));
print(recall_score(y_test,pred));

scores = cross_val_score(clf, df_scaled, target, cv=5)
print(scores)

0.73127753304
[[86 26]
 [35 80]]
0.754716981132
0.695652173913
[ 0.73626374  0.66483516  0.73626374  0.67955801  0.68888889]


In [88]:
from sklearn.metrics import log_loss
clf = svm.SVC(probability=True)

pred_prob = clf.fit(x_train_scaled, y_train).predict_proba(x_test_scaled)
log_loss(y_test,pred_prob)

0.54205787208790879

In [63]:
# knn
k = 5
from sklearn.neighbors import KNeighborsClassifier
nei = KNeighborsClassifier(n_neighbors=k)

print(nei.fit(x_train, y_train).score(x_test,y_test));

pred = nei.fit(x_train, y_train).predict(x_test)
confusion = confusion_matrix(y_test,pred)
print(confusion);
print(precision_score(y_test,pred));
print(recall_score(y_test,pred));

scores = cross_val_score(nei, df, target, cv=5)
print(scores)

0.68281938326
[[82 30]
 [42 73]]
0.708737864078
0.634782608696
[ 0.64835165  0.6043956   0.67032967  0.6519337   0.57222222]


In [79]:
# log with lasso
log = LogisticRegression(penalty='l1').fit(x_train_scaled, y_train)
print(log.score(x_test_scaled,y_test));

pred = log.predict(x_test_scaled)
confusion = confusion_matrix(y_test,pred)
print(confusion);
print(precision_score(y_test,pred));
print(recall_score(y_test,pred));

logreg = LogisticRegression()
scores = cross_val_score(logreg, df_scaled, target, cv=5)

0.722466960352
[[86 26]
 [37 78]]
0.75
0.678260869565


In [82]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
bdt = AdaBoostClassifier(DecisionTreeClassifier(max_depth=5),
                         algorithm="SAMME",
                         n_estimators=200)
print(bdt.fit(x_train, y_train).score(x_test,y_test));

pred = bdt.fit(x_train, y_train).predict(x_test)
confusion = confusion_matrix(y_test,pred)
print(confusion);
print(precision_score(y_test,pred));
print(recall_score(y_test,pred));

scores = cross_val_score(bdt, df, target, cv=5)
print(scores)

0.722466960352
[[84 28]
 [38 77]]
0.733333333333
0.669565217391
[ 0.65384615  0.64835165  0.6978022   0.69060773  0.61111111]


In [94]:
seed = df['different_seed']
x_train, x_test, y_train, y_test = train_test_split(seed, target, random_state=0)
x_train = x_train.reshape(-1,1)
x_test = x_test.reshape(-1,1)
log = LogisticRegression().fit(x_train, y_train)
print(log.score(x_test,y_test));
# the accuracy sames to be good, see p and r
pred = log.predict(x_test)
confusion = confusion_matrix(y_test,pred)
print(confusion);
print(precision_score(y_test,pred));
print(recall_score(y_test,pred))

0.709251101322
[[84 28]
 [38 77]]
0.733333333333
0.669565217391


/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:3: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead
  app.launch_new_instance()
/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:4: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead


In [95]:
log = LogisticRegression()
pred_prob = log.fit(x_train, y_train).predict_proba(x_test)
log_loss(y_test,pred_prob)

0.5512875090984819

In [1]:
data.head()

NameError: name 'data' is not defined