In [83]:
# import packages
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.metrics import confusion_matrix, precision_score, recall_score
from sklearn.model_selection import cross_val_score
from sklearn.metrics import log_loss

from sklearn.linear_model import LogisticRegression
from sklearn import svm
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier

scaler = preprocessing.MinMaxScaler()

In [84]:
# data preparation
# game --> team
# team --> game
# write all data into csv

In [85]:
# model construction
# read data 
data = pd.read_csv("all_data.csv")
target = data['result']

In [86]:
# seed difference

seed = data['different_seed']

x_train, x_test, y_train, y_test = train_test_split(seed, target, random_state=0)
x_train = x_train.reshape(-1,1)
x_test = x_test.reshape(-1,1)

# logistic regression

log = LogisticRegression()
print("accuracy:",log.fit(x_train, y_train).score(x_test,y_test));

pred = log.predict(x_test)
confusion = confusion_matrix(y_test,pred)
print("confusion matrix:\n",confusion);
print("P:",precision_score(y_test,pred));
print("R:",recall_score(y_test,pred))

pred_prob = log.fit(x_train, y_train).predict_proba(x_test)
print("log_loss:",log_loss(y_test,pred_prob))

accuracy: 0.71615720524
confusion matrix:
 [[88 37]
 [28 76]]
P: 0.672566371681
R: 0.730769230769
log_loss: 0.532172798705


/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:6: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead
/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:7: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead


In [87]:
# all other difference
data0 = data.iloc[:,51:65]
data1 = data.iloc[:,1:3]
data0 = pd.concat([data1,data0], axis=1)
data0 = pd.concat([data['team1'],data0], axis=1)
data0 = pd.concat([data['result'],data0], axis=1)
data0 = data0.dropna()
data0.head()

result  team1  team2  Season  diff_score  diff_fgm  diff_fga  diff_fgm3  \
0       1   1112   1125    2013    3.618750  2.602083  0.310417   0.643750   
1       0   1116   1137    2006   -8.012236 -3.516129 -8.914349   0.324805   
2       0   1137   1139    2013    1.174242 -0.154356  0.457386   1.920455   
3       1   1112   1156    2009   -7.218750 -2.625000  0.093750  -1.437500   
4       1   1124   1160    2012   -7.991477 -3.372159 -4.312500  -1.164773   

   diff_fga3  diff_ftm  diff_fta   diff_or   diff_dr  diff_ast   diff_to  \
0   1.006250 -2.229167 -2.679167 -2.164583 -1.885417  1.956250  0.472917   
1  -1.220245 -1.304783 -1.796440 -2.883204 -0.459399 -0.962180  1.095662   
2   6.216856 -0.437500  0.989583  2.574811 -2.246212 -0.558712  3.835227   
3  -0.312500 -0.531250  0.093750  0.468750 -0.656250 -1.000000 -0.125000   
4  -1.535985 -0.082386  1.825758 -2.558712  1.340909 -3.352273 -1.285985   

   diff_stl  diff_blk   diff_pf  
0  2.595833 -1.172917  1.856250  
1  0.272525 -4.439377  0.616240  
2  2.166667 -1.759470  3.404356  
3  2.625000  0.218750  2.750000  
4 -1.761364 -1.386364 -0.542614

In [88]:
df = data0.iloc[:,4:18]
target = data0['result']

x_train, x_test, y_train, y_test = train_test_split(df, target, random_state=0)

x_train_scaled = scaler.fit(x_train).transform(x_train)
x_test_scaled = scaler.fit(x_train).transform(x_test)
df_scaled = scaler.fit_transform(df)

In [89]:
# logistic regression
log = LogisticRegression()
print("accuracy:",log.fit(x_train, y_train).score(x_test,y_test));

pred = log.predict(x_test)
confusion = confusion_matrix(y_test,pred)
print("confusion matrix:\n",confusion);
print("P:",precision_score(y_test,pred));
print("R:",recall_score(y_test,pred));

pred_prob = log.fit(x_train, y_train).predict_proba(x_test)
print("log_loss:",log_loss(y_test,pred_prob))

accuracy: 0.638766519824
confusion matrix:
 [[72 40]
 [42 73]]
P: 0.646017699115
R: 0.634782608696
log_loss: 0.605148199814


In [90]:
# logistic regression using scaled data
log = LogisticRegression()
print("accuracy:",log.fit(x_train_scaled, y_train).score(x_test_scaled,y_test));

pred = log.predict(x_test_scaled)
confusion = confusion_matrix(y_test,pred)
print("confusion matrix:\n",confusion);
print("P:",precision_score(y_test,pred));
print("R:",recall_score(y_test,pred));

pred_prob = log.fit(x_train_scaled, y_train).predict_proba(x_test_scaled)
print("log_loss:",log_loss(y_test,pred_prob))

accuracy: 0.678414096916
confusion matrix:
 [[78 34]
 [39 76]]
P: 0.690909090909
R: 0.660869565217
log_loss: 0.603924386801


In [91]:
# svm
clf = svm.SVC()

print("accuracy:",clf.fit(x_train, y_train).score(x_test,y_test));

pred = clf.fit(x_train, y_train).predict(x_test)
confusion = confusion_matrix(y_test,pred)
print("confusion matrix:\n",confusion);
print("P:",precision_score(y_test,pred));
print("R:",recall_score(y_test,pred));

clf = svm.SVC(probability=True)
pred_prob = clf.fit(x_train, y_train).predict_proba(x_test)
print("log_loss:",log_loss(y_test,pred_prob))

accuracy: 0.546255506608
confusion matrix:
 [[82 30]
 [73 42]]
P: 0.583333333333
R: 0.365217391304
log_loss: 0.685906620939


In [92]:
# svm using scaled data
clf = svm.SVC()

print("accuracy:",clf.fit(x_train_scaled, y_train).score(x_test_scaled,y_test));

pred = clf.fit(x_train_scaled, y_train).predict(x_test_scaled)
confusion = confusion_matrix(y_test,pred)
print("confusion matrix:\n",confusion);
print("P:",precision_score(y_test,pred));
print("R:",recall_score(y_test,pred));

clf = svm.SVC(probability=True)
pred_prob = clf.fit(x_train_scaled, y_train).predict_proba(x_test_scaled)
print("log_loss:",log_loss(y_test,pred_prob))

accuracy: 0.660792951542
confusion matrix:
 [[82 30]
 [47 68]]
P: 0.69387755102
R: 0.591304347826
log_loss: 0.604725501994


In [93]:
# all difference with seed difference
data0 = data.iloc[:,50:65]
data1 = data.iloc[:,1:3]
data0 = pd.concat([data1,data0], axis=1)
data0 = pd.concat([data['team1'],data0], axis=1)
data0 = pd.concat([data['result'],data0], axis=1)
data0 = data0.dropna()
data0.head()

result  team1  team2  Season  different_seed  diff_score  diff_fgm  \
0       1   1112   1125    2013              -5    3.618750  2.602083   
1       0   1116   1137    2006              -1   -8.012236 -3.516129   
2       0   1137   1139    2013               5    1.174242 -0.154356   
3       1   1112   1156    2009              -1   -7.218750 -2.625000   
4       1   1124   1160    2012              -8   -7.991477 -3.372159   

   diff_fga  diff_fgm3  diff_fga3  diff_ftm  diff_fta   diff_or   diff_dr  \
0  0.310417   0.643750   1.006250 -2.229167 -2.679167 -2.164583 -1.885417   
1 -8.914349   0.324805  -1.220245 -1.304783 -1.796440 -2.883204 -0.459399   
2  0.457386   1.920455   6.216856 -0.437500  0.989583  2.574811 -2.246212   
3  0.093750  -1.437500  -0.312500 -0.531250  0.093750  0.468750 -0.656250   
4 -4.312500  -1.164773  -1.535985 -0.082386  1.825758 -2.558712  1.340909   

   diff_ast   diff_to  diff_stl  diff_blk   diff_pf  
0  1.956250  0.472917  2.595833 -1.172917  1.856250  
1 -0.962180  1.095662  0.272525 -4.439377  0.616240  
2 -0.558712  3.835227  2.166667 -1.759470  3.404356  
3 -1.000000 -0.125000  2.625000  0.218750  2.750000  
4 -3.352273 -1.285985 -1.761364 -1.386364 -0.542614

In [94]:
df = data0.iloc[:,4:18]
target = data0['result']

x_train, x_test, y_train, y_test = train_test_split(df, target, random_state=0)

x_train_scaled = scaler.fit(x_train).transform(x_train)
x_test_scaled = scaler.fit(x_train).transform(x_test)
df_scaled = scaler.fit_transform(df)

# logistic regression
log = LogisticRegression()
print("accuracy:",log.fit(x_train, y_train).score(x_test,y_test));

pred = log.predict(x_test)
confusion = confusion_matrix(y_test,pred)
print("confusion matrix:\n",confusion);
print("P:",precision_score(y_test,pred));
print("R:",recall_score(y_test,pred));

pred_prob = log.fit(x_train, y_train).predict_proba(x_test)
print("log_loss:",log_loss(y_test,pred_prob))

accuracy: 0.709251101322
confusion matrix:
 [[83 29]
 [37 78]]
P: 0.728971962617
R: 0.678260869565
log_loss: 0.548221113352


In [95]:
# logistic regression using scaled data
log = LogisticRegression()
print("accuracy:",log.fit(x_train_scaled, y_train).score(x_test_scaled,y_test));

pred = log.predict(x_test_scaled)
confusion = confusion_matrix(y_test,pred)
print("confusion matrix:\n",confusion);
print("P:",precision_score(y_test,pred));
print("R:",recall_score(y_test,pred));

pred_prob = log.fit(x_train_scaled, y_train).predict_proba(x_test_scaled)
print("log_loss:",log_loss(y_test,pred_prob))

accuracy: 0.718061674009
confusion matrix:
 [[86 26]
 [38 77]]
P: 0.747572815534
R: 0.669565217391
log_loss: 0.550236931041


In [96]:
# svm
clf = svm.SVC()

print("accuracy:",clf.fit(x_train, y_train).score(x_test,y_test));

pred = clf.fit(x_train, y_train).predict(x_test)
confusion = confusion_matrix(y_test,pred)
print("confusion matrix:\n",confusion);
print("P:",precision_score(y_test,pred));
print("R:",recall_score(y_test,pred));

clf = svm.SVC(probability=True)
pred_prob = clf.fit(x_train, y_train).predict_proba(x_test)
print("log_loss:",log_loss(y_test,pred_prob))

accuracy: 0.581497797357
confusion matrix:
 [[92 20]
 [75 40]]
P: 0.666666666667
R: 0.347826086957
log_loss: 0.661858129374


In [97]:
# svm using scaled data
clf = svm.SVC()

print("accuracy:",clf.fit(x_train_scaled, y_train).score(x_test_scaled,y_test));

pred = clf.fit(x_train_scaled, y_train).predict(x_test_scaled)
confusion = confusion_matrix(y_test,pred)
print("confusion matrix:\n",confusion);
print("P:",precision_score(y_test,pred));
print("R:",recall_score(y_test,pred));

clf = svm.SVC(probability=True)
pred_prob = clf.fit(x_train_scaled, y_train).predict_proba(x_test_scaled)
print("log_loss:",log_loss(y_test,pred_prob))

accuracy: 0.726872246696
confusion matrix:
 [[86 26]
 [36 79]]
P: 0.752380952381
R: 0.686956521739
log_loss: 0.544766890539


In [98]:
# only score and win rate with scale
data0 = data.dropna()
df = data0[['score1','score2','rate1','rate2']]
target = data0['result']

x_train, x_test, y_train, y_test = train_test_split(df, target, random_state=0)

x_train_scaled = scaler.fit(x_train).transform(x_train)
x_test_scaled = scaler.fit(x_train).transform(x_test)
df_scaled = scaler.fit_transform(df)

# logistic regression
log = LogisticRegression()
print("accuracy:",log.fit(x_train, y_train).score(x_test,y_test));

pred = log.predict(x_test)
confusion = confusion_matrix(y_test,pred)
print("confusion matrix:\n",confusion);
print("P:",precision_score(y_test,pred));
print("R:",recall_score(y_test,pred));

pred_prob = log.fit(x_train, y_train).predict_proba(x_test)
print("log_loss:",log_loss(y_test,pred_prob))

accuracy: 0.656387665198
confusion matrix:
 [[77 35]
 [43 72]]
P: 0.672897196262
R: 0.626086956522
log_loss: 0.632094655657


In [101]:
data.head()

Unnamed: 0  team2  Season       fgm1       fga1     fgm31      fga31  \
0           0   1125    2013  27.633333  55.966667  8.300000  22.100000   
1           1   1137    2006  23.000000  48.827586  6.034483  15.586207   
2           2   1139    2013  23.939394  53.363636  6.545455  19.060606   
3           3   1156    2009  23.031250  54.156250  4.750000  15.343750   
4           4   1160    2012  22.718750  51.687500  5.562500  16.312500   

        ftm1       fta1        or1    ...     diff_fga3  diff_ftm  diff_fta  \
0  13.333333  18.133333   9.366667    ...      1.006250 -2.229167 -2.679167   
1  14.275862  20.655172   9.310345    ...     -1.220245 -1.304783 -1.796440   
2  14.000000  20.333333  11.606061    ...      6.216856 -0.437500  0.989583   
3  14.156250  20.093750  11.562500    ...     -0.312500 -0.531250  0.093750   
4  15.281250  22.250000   9.562500    ...     -1.535985 -0.082386  1.825758   

    diff_or   diff_dr  diff_ast   diff_to  diff_stl  diff_blk   diff_pf  
0 -2.164583 -1.885417  1.956250  0.472917  2.595833 -1.172917  1.856250  
1 -2.883204 -0.459399 -0.962180  1.095662  0.272525 -4.439377  0.616240  
2  2.574811 -2.246212 -0.558712  3.835227  2.166667 -1.759470  3.404356  
3  0.468750 -0.656250 -1.000000 -0.125000  2.625000  0.218750  2.750000  
4 -2.558712  1.340909 -3.352273 -1.285985 -1.761364 -1.386364 -0.542614  

[5 rows x 65 columns]